### ISSUE TITLE
Morse simulation

### ISSUE THREAD

**Issue by cburbridge** [strands-project/g4s_deployment#4]
Create a 'reasonably' accurate simulation of the G4S deployment environment. This should include desks and other furniture, offices etc.

@mudrole1 / @ferdianjovan to create this.

**Comment by marc-hanheide** [comment]
@jailander has just created this for AAF from a slam map in a rather convenient way. Maybe he can advise.

**Comment by hawesie** [comment]
Please!

**Comment by Jailander** [comment]
Hi, 

I just followed Marc's Idea of taking the 2d map and extruding it to 3D like this tutorial shows, https://www.youtube.com/watch?v=ows2QTiMRPg once you've done that you should check that the scale is according.
I used the ruler/protractor tool on Blender and measured a bit of the environment of which you previously know the size, I made a 20 pixels mark on the Slam and measured and scale the model until that mark measured 1m wide.
Then check if you can see the model on the game engine, if not you need to export to .x3d format and the import again (I know horrible hack if someone with more blender skills knows a better way please say I).

**Comment by cburbridge** [comment]
Here are the measurements of the desks in the open plan area:

![img_20150311_094003](https://cloud.githubusercontent.com/assets/259580/6593797/7729c518-c7d3-11e4-9630-f80fcc91b8e0.jpg)

**Comment by mudrole1** [comment]
Do you know the height of the table?

**Comment by cburbridge** [comment]
Desk height: 71.5cm
Dividers at side of open area height: 120cm
Between desk screen/divider height: max 43cm, min 22cm

**Comment by mudrole1** [comment]
created pull request in strands_morse  #102 with first version of the environment. I dont know how offices looks like, so they are not populated by furniture.

**Comment by hawesie** [comment]
I've seen this running, but the morse package needs a bit more. Please can someone add the metric map to the morse package plus suitable a g4s_nav launch file for the simulation too?

Also, does anyone have a top map for this yet?
